import React, { useState } from 'react';
import { Lock, FileSpreadsheet, ShieldCheck, Download, ArrowLeft } from 'lucide-react';
import { Organization, ReportShareLink } from '../types';
import { getStore, formatCurrency } from '../lib/storage';

interface SharedReportViewProps {
  shareCode: string;
  organization: Organization;
  onBack: () => void;
}

export const SharedReportView: React.FC<SharedReportViewProps> = ({
  shareCode,
  organization,
  onBack
}) => {
  const store = getStore();
  const shareLink = store.shareLinks.find(s => s.shareCode === shareCode && s.orgId === organization.id);

  const [enteredPasscode, setEnteredPasscode] = useState('');
  const [isAuthenticated, setIsAuthenticated] = useState(!shareLink?.passcode);
  const [errorMsg, setErrorMsg] = useState('');

  const isExpired = Boolean(shareLink?.expiresAt && new Date(shareLink.expiresAt) < new Date());
  if (!shareLink || shareLink.isRevoked || isExpired) {
    return (
      <div className="max-w-md mx-auto my-16 p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-center space-y-4">
        <Lock className="w-12 h-12 text-rose-500 mx-auto" />
        <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">Link Invalid or Revoked</h2>
        <p className="text-xs text-slate-500">This secure report link has either expired, been revoked, or does not exist.</p>
        <button onClick={onBack} className="px-4 py-2 rounded-xl bg-slate-100 text-slate-700 font-bold text-xs">
          Return to Application
        </button>
      </div>
    );
  }

  const handleAuthenticate = (e: React.FormEvent) => {
    e.preventDefault();
    if (enteredPasscode === shareLink.passcode) {
      setIsAuthenticated(true);
      setErrorMsg('');
    } else {
      setErrorMsg('Incorrect passcode. Access denied.');
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="max-w-md mx-auto my-16 p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl space-y-4">
        <div className="text-center space-y-1">
          <Lock className="w-10 h-10 text-purple-600 mx-auto" />
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">Passcode Protected Report</h2>
          <p className="text-xs text-slate-500">Enter the authorized passcode to view this read-only report.</p>
        </div>

        {errorMsg && <div className="p-2.5 rounded-xl bg-rose-50 text-rose-600 text-xs font-semibold">{errorMsg}</div>}

        <form onSubmit={handleAuthenticate} className="space-y-3">
          <input
            type="password"
            required
            placeholder="Enter passcode..."
            value={enteredPasscode}
            onChange={e => setEnteredPasscode(e.target.value)}
            className="w-full p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs"
          />
          <button type="submit" className="w-full py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs">
            Unlock Report
          </button>
        </form>
      </div>
    );
  }

  const receipts = store.receipts.filter(r => r.orgId === organization.id);

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12 animate-in fade-in">
      <div className="flex items-center justify-between">
        <button onClick={onBack} className="flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-slate-800">
          <ArrowLeft className="w-4 h-4" />
          <span>Exit Reader Mode</span>
        </button>

        <span className="px-3 py-1 rounded-full bg-purple-100 text-purple-700 font-bold text-xs flex items-center gap-1">
          <ShieldCheck className="w-3.5 h-3.5" /> Read-Only Shared Portal
        </span>
      </div>

      <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl space-y-6">
        <div className="border-b border-slate-200 dark:border-slate-800 pb-4">
          <span className="text-[10px] font-bold uppercase text-purple-600 font-mono">LEDGERNEST OFFICIAL REPORT</span>
          <h1 className="text-xl font-bold text-slate-900 dark:text-slate-100 mt-1">{shareLink.reportTitle}</h1>
          <div className="text-xs text-slate-500 mt-1">Generated by {shareLink.createdBy} • Organization: {organization.name}</div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-800 text-slate-500 font-bold">
                <th className="p-3">Ref Number</th>
                <th className="p-3">Date</th>
                <th className="p-3">Party</th>
                <th className="p-3 text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {receipts.map(r => (
                <tr key={r.id}>
                  <td className="p-3 font-mono font-bold">{r.receiptNumber}</td>
                  <td className="p-3">{r.date}</td>
                  <td className="p-3 font-semibold">{r.receivedFrom}</td>
                  <td className="p-3 text-right font-bold text-emerald-600">{formatCurrency(r.amount, organization.currency)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
